apiVersion: v1
kind: Service
metadata:
  name: staysync-api
  namespace: staysync
spec:
  selector:
    app: staysync-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
